language: cpp
sudo: required
dist: trusty
compiler:
  - clang
  - gcc
os: linux
before_install: 
  - sudo apt-get -qq update
  - sudo apt-get install -y libopencv-core-dev libopencv-highgui-dev
script: mkdir build && cd build && cmake .. && make